name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/arm64
      - name: Setup buildx
        uses: docker/setup-buildx-action@v2.4.1
        with:
          platforms: linux/arm64
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_ADDRESS }}/${{ DOCKER>REGISTRY_USERNAME }}/blog:latest
          platforms: linux/arm64
